name: Build and Deploy Docker Image

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t test-flask-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker tag test-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/test-flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/test-flask-app:latest
